### ISSUE TITLE
Unable to create package if multiple .exe files exist even if entry point specified

### ISSUE THREAD

**Issue by blpblp1212** [mansellan/clickonce#37]
I set argument --entryPoint, but I get bug 'Unable to infer entry point, multiple .exe files found' anyway. I determined entryPoint in input parameters.. --entryPoint OdipDesktop.exe

In devOps I get the same error

![image](https://user-images.githubusercontent.com/77333170/104314691-13fec700-54da-11eb-80d5-a0e4a9810005.png)

![image](https://user-images.githubusercontent.com/77333170/104314717-1e20c580-54da-11eb-8e47-6ef7b6d4d5bc.png)

Could you help me with this Issue

**Comment by mansellan** [comment]
Hi, thanks for reporting this. I'll take a look.

**Comment by mansellan** [comment]
I took the liberty of editing the issue title, hope you don't mind. This is now fixed and released as v1.1.1.

Thanks again for reporting this!
