### ISSUE TITLE
.net 5?

### ISSUE THREAD

**Issue by dg107** [mansellan/clickonce#45]
Can you add .net 5 to the supported framework versions?

**Comment by mansellan** [comment]
For pre-requisites installation? If so then yes, that should be easy enough. The only possible snag could be that Microsoft are still regularly patching .net 5, whereas the pre-requisite specifications are "burnt into" the extension (static XML files).

If I added the current .net 5 runtime, but didn't update it every patch, would that suffice?

**Comment by dg107** [comment]
I was just trying to figure out how to use clickonce and dev ops with a .net 5 desktop project. I finally gave up on it and set up an inno installer and wrote my own update mechanism to download and launch the installer when a new version is available.

⁣Get BlueMail for Android ​

**Comment by mansellan** [comment]
OK, sorry to hear you had problems. This is a standard use-case and should "just work". I have several .net 5 desktop apps set up in Azure DevOps, so it's disappointing it didn't work for you.

Closing issue as you've gone with Inno, but thanks for reporting.
